version: "3.7"
services:
    rts-app:
        build:
            context: ./
            dockerfile: Dockerfile
        image: rts-app:1.0
        container_name: rts-app
        restart: unless-stopped
        working_dir: /var/www/rts-app
        ports:
            - "8090:80"
        volumes:
            - ./:/var/www/rts-app
            - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
volumes:
    mysql_data:
networks:
    default:
        external: true
        name: cicd
