version: "3.7"
services:
    rts-app:
        build:
            context: ./
            dockerfile: Dockerfile
        image: rts-app:1.0
        container_name: rts-app
        restart: unless-stopped
        working_dir: /var/www/rts-app
        ports:
            - "8090:80"
        volumes:
            - ./:/var/www/rts-app
            - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
        depends_on:
            - mysql-db
    mysql-db:
        image: mysql:8.0.32
        restart: always
        container_name: mysql-db
        ports:
            - 3308:3306
        environment:
            MYSQL_DATABASE: music
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: music
            MYSQL_PASSWORD: music
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - mysql_data:/var/lib/mysql
volumes:
    mysql_data:            
networks:
    default:
        external: true
        name: cicd
